raw:
  zip: "raw/cjp_tables_old.zip"
  article_text: "raw/newsarticles_article.parquet"
  comm_areas: "raw/CommAreas_2025.csv"
  neighborhoods: "raw/Neighborhoods_2025.csv"
  parks: "raw/Parks_2025.csv"
  street_names: "raw/StreetNames_2025.csv"
  street_segs: "raw/StreetSegments_2025.geojson"

prior_model:
  article_text_filtered: "pre_relevance/articles.parquet"
  geocodes: "prior_model/geocodes.parquet"
  user_coding: "prior_model/user_coding.parquet"

art_relevance:
  # This is JSON because Label-Studio doesn't accept jsonl!
  article_text_pre_annotate: "art_relevance/articles_pre_annotate.json"
  article_text_labeled_verbose: "art_relevance/articles_labeled_verbose.json"
  article_text_labeled: "art_relevance/articles_labeled.jsonl"
  article_text_train: "art_relevance/articles_train.spacy"
  article_text_dev: "art_relevance/articles_dev.spacy"
  article_text_test: "art_relevance/articles_test.spacy"
  article_text_filtered: "art_relevance/articles_filtered.parquet"

sent_relevance:
  # This is JSON because Label-Studio doesn't accept jsonl!
  article_text_pre_annotate: "sent_relevance/articles_pre_annotate.json"
  article_text_labeled_verbose: "sent_relevance/articles_labeled_verbose.json"
  article_text_labeled: "sent_relevance/articles_labeled.jsonl"
  article_text_train: "sent_relevance/articles_train.spacy"
  article_text_dev: "sent_relevance/articles_dev.spacy"
  article_text_test: "sent_relevance/articles_test.spacy"
  article_text_filtered: "sent_relevance/articles_filtered.spacy"
  
geoms:
  comm_areas: "geoms/comm_areas.parquet"
  neighborhoods: "geoms/neighborhoods.parquet"
  street_names: "geoms/street_names.csv"
  street_segs: "geoms/street_segments.parquet"
  street_blocks: "geoms/street_blocks.parquet"
  street_intersections: "geoms/street_crosses.parquet"
  street_intersection_points: "geoms/street_cross_points.parquet"
  parks: "geoms/parks.csv"
  landmarks: "geoms/landmarks.parquet"
  hospitals: "geoms/hospitals.parquet"
  block_labels: "geoms/block_labels.parquet"
  intersection_labels: "geoms/street_cross_labels.parquet"
  neighborhood_labels: "geoms/neighborhood_labels.csv"

entity_recognition:
  # Splitting first because only want to look at train data when
  # developing heurstics for NER.
  article_text_train: "entity_recognition/articles_train.spacy"
  article_text_dev: "entity_recognition/articles_dev.spacy"
  article_text_test: "entity_recognition/articles_test.spacy"
  prelabel_train: "entity_recognition/prelabels_train.json"
  prelabel_dev: "entity_recognition/prelabels_dev.json"
  labels_train_verbose: "entity_recognition/labels_train_verbose.json"
  labels_dev_verbose: "entity_recognition/labels_dev_verbose.json"
  labels_train: "entity_recognition/labels_train.spacy"
  labels_dev: "entity_recognition/labels_dev.spacy"
  inference: "entity_recognition/predictions.spacy"

neighborhood_clf:
  geocodes: "neighborhood_clf/geocodes.parquet"
  ner_labels: "neighborhood_clf/ner_labels.parquet"
  synth_data: "neighborhood_clf/synthetic_data.spacy"
  train: "neighborhood_clf/train.spacy"
  dev: "neighborhood_clf/dev.spacy"
  test: "neighborhood_clf/test.spacy"
  eval_metrics: "neighborhood_clf/test_meta.json"
  eval_data: "neighborhood_clf/test_eval.spacy"
  inference: "neighborhood_clf/predictions.spacy"