raw:
  zip: "raw/cjp_tables_old.zip"
  article_text: "raw/newsarticles_article.parquet"
  comm_areas: "raw/CommAreas_2025.csv"
  neighborhoods: "raw/Neighborhoods_2025.csv"
  parks: "raw/Parks_2025.csv"
  street_names: "raw/StreetNames_2025.csv"
  street_segs: "raw/StreetSegments_2025.geojson"

pre_relevance:
  article_text_filtered: "pre_relevance/articles.parquet"

art_relevance:
  # This is JSON because Label-Studio doesn't accept jsonl!
  article_text_pre_annotate: "art_relevance/articles_pre_annotate.json"
  article_text_labeled_verbose: "art_relevance/articles_labeled_verbose.json"
  article_text_labeled: "art_relevance/articles_labeled.jsonl"
  article_text_train: "art_relevance/articles_train.spacy"
  article_text_dev: "art_relevance/articles_dev.spacy"
  article_text_test: "art_relevance/articles_test.spacy"
  article_text_filtered: "art_relevance/articles_filtered.parquet"

sent_relevance:
  # This is JSON because Label-Studio doesn't accept jsonl!
  article_text_pre_annotate: "sent_relevance/articles_pre_annotate.json"
  article_text_labeled_verbose: "sent_relevance/articles_labeled_verbose.json"
  article_text_labeled: "sent_relevance/articles_labeled.jsonl"
  article_text_train: "sent_relevance/articles_train.spacy"
  article_text_dev: "sent_relevance/articles_dev.spacy"
  article_text_test: "sent_relevance/articles_test.spacy"
  article_text_filtered: "sent_relevance/articles_filtered.parquet"
  
geoms:
  comm_areas: "geoms/comm_areas.parquet"
  neighborhoods: "geoms/neighborhoods.csv"
  street_names: "geoms/street_names.csv"
  street_segs: "geoms/street_segments.parquet"
  street_blocks: "geoms/street_blocks.parquet"
  street_intersections: "geoms/street_crosses.parquet"
  parks: "geoms/parks.csv"
  landmarks: "geoms/landmarks.parquet"
  hospitals: "geoms/hospitals.parquet"
  block_labels: "geoms/block_labels.parquet"

entity_recognition:
  explore: "entity_recognition/explore.spacy"
  article_text_train: "entity_recognition/articles_train.spacy"
  article_text_dev: "entity_recognition/articles_dev.spacy"
  article_text_test: "entity_recognition/articles_test.spacy"
  prelabel_train: "entity_recognition/prelabels_train.json"
  prelabel_dev: "entity_recognition/prelabels_dev.json"
  labels_train_verbose: "entity_recognition/labels_train_verbose.json"
  labels_dev_verbose: "entity_recognition/labels_dev_verbose.json"
  labels_train: "entity_recognition/labels_train.spacy"
  labels_dev: "entity_recognition/labels_dev.spacy"
  inference: "entity_recognition/predictions.spacy"
