art_relevance:
  base_cfg: "scripts/art_relevance/spacy_base_config.cfg"
  full_cfg: "scripts/art_relevance/spacy_config.cfg"
  base_model: "en_core_web_sm"
  trained_model: "models/art_relevance/"
  optuna_db: "sqlite:///optuna.sqlite3"
  proto_seed: 31525
  k: 200
  
sent_relevance:
  base_cfg: "scripts/sent_relevance/spacy_base_config.cfg"
  full_cfg: "scripts/sent_relevance/spacy_config.cfg"
  base_model: "en_core_web_sm"
  trained_model: "models/sent_relevance/"
  optuna_db: "sqlite:///optuna.sqlite3"
  proto_seed: 31925

dagster:
  dagster_home: ".dagster_home"

entity_recognition:
  base_model: "en_core_web_sm"
  optuna_db: "sqlite:///optuna.sqlite3"
  base_cfg: "scripts/entity_recognition/spacy_base_config.cfg"
  full_cfg: "scripts/entity_recognition/spacy_config.cfg"
  trained_model: "models/entity_recognition/"