art_relevance:
  base_cfg: "scripts/art_relevance/spacy_base_config.cfg"
  full_cfg: "scripts/art_relevance/spacy_config.cfg"
  base_model: "en_core_web_sm"
  trained_model: "models/art_relevance/"
  optuna_db: "sqlite:///optuna.sqlite3"

sent_relevance:
  base_cfg: "scripts/sent_relevance/spacy_base_config.cfg"
  full_cfg: "scripts/sent_relevance/spacy_config.cfg"
  base_model: "en_core_web_sm"
  trained_model: "models/sent_relevance/"
  optuna_db: "sqlite:///optuna.sqlite3"

dagster:
  dagster_home: ".dagster_home"